//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day10_L1_L9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public short OrderId { get; set; }
        public string OrderName { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public string OrderDate { get; set; }
        public Nullable<short> CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
